### ISSUE TITLE
Does not work with omniauth 2.0

### ISSUE THREAD

**Issue by julienchabanon** [jgraichen/omniauth-kerberos#5]
My omniauth initializer:
```
OmniAuth.config.logger = Rails.logger
OmniAuth.config.allowed_request_methods = [:post, :get]
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :kerberos, fields: [:login, :pwd]
  provider :google_oauth2, provider_ignores_state: true, setup: GoogleOauth2Setup
  provider :linkedin, provider_ignores_state: true, setup: LinkedinSetup
  provider :microsoft_graph, provider_ignores_state: true, setup: MicrosoftGraphSetup
  provider :saml, setup: SamlSetup
end
```

Adding `provider :kerberos, fields: [:login, :pwd]` create the error `NoMethodError (undefined method `[]' for nil)`
Removing it fix the issue

The kerberos strategy works perfectly fine with omniauth 1.9.X

**Comment by julienchabanon** [comment]
The issue comes from omniauth-multipassword, even in version 2.0.0-rc1.

**Comment by julienchabanon** [comment]
Since this project has not been updated in years, I created a fork that is compatible with omniauth 2.X and is not using omniauth-multipassword.
https://github.com/julienchabanon/omniauth-kerberos-clearlyip

**Comment by jgraichen** [comment]
@julienchabanon Hi, I'll check asap. If you have a working patch and would like to contribute, please send me a merge request. :pray:

**Comment by jgraichen** [comment]
@julienchabanon The issue appeared with `omniauth` 2.1 which supported newer `rack` versions. These removed some older ways to access request parameters, which `omniauth-multipass` (and by inheritance `omniauth-kerberos`) used.

I've upgraded both gems to work with the newest `rack` and `omniauth`. Please try version `0.4.0` for `omniauth-kerberos`.

**Comment by julienchabanon** [comment]
> @julienchabanon The issue appeared with `omniauth` 2.1 which supported newer `rack` versions. These removed some older ways to access request parameters, which `omniauth-multipass` (and by inheritance `omniauth-kerberos`) used.
> 
> I've upgraded both gems to work with the newest `rack` and `omniauth`. Please try version `0.4.0` for `omniauth-kerberos`.

Awesome man, thanks for the update!
